### ISSUE TITLE
National varieties of Chinese

### ISSUE THREAD

**Issue by 1ec5** [amishas157/lookup-osm-wikidata#1]
FYI, some Wikidata entities may have labels in `zh-cn`, `zh-hk`, `zh-mo`, `zh-sg`, or `zh-tw`. Should scripts like [lookUpChinese.py](https://github.com/amishas157/osm-wikidata/blob/Improvements/scripts/lookUpChinese.py) and [findingchinese.py](https://github.com/amishas157/osm-wikidata/blob/Improvements/scripts/findingchinese.py) take these labels into account? `zh-cn` and `zh-sg` could be considered equivalent to `zh-hans`, while `zh-hk`, `zh-mo`, and `zh-tw` could be considered equivalent to `zh-hant`.

**Comment by amishas157** [comment]
@1ec5 
These scripts have been generalized to return translation for multiple number of language codes ,given as parameter.

**Comment by bsrinivasa** [comment]
The tool has the capabilities to query desired languages from OSM and Wikidata Thanks everyone. Closing the issue.
