### ISSUE TITLE
Standardized field names and conventions

### ISSUE THREAD

**Issue by planemad** [amishas157/lookup-osm-wikidata#2]
Lets standardize field names in the CSV to make it more predictable for the various scripts while processing CSVs:

**Input**
- `name`: _string_ common local name of the feature as given
- `osm_id`: _long int_ of the unique id for the particular node, way or relation
- `osm_type`: _string_ describing the OSM feature type. Either node, way or relation
- `osm_lat` `osm_lon`: _float_ latitude and longitude of the centroid of the feature on OSM
- `osm_wikidata`: _string_ unique QID of the corresponding OSM feature in Wikidata

**Output**
- Prefix all fields from results from querying Wikidata with `wiki_` and for results from OSM with `osm_`
- `wiki_osm_distance` _float_ distance between feature centroid location on OSM and Wikidata in Km

cc @amishas157 @bsrinivasa

**Comment by amishas157** [comment]
@planemad 

Keeping in mind the standardized field names , the output columns names from OSM Script `osm.py` and Wiki Script `wiki.py` is appended with `osm:` and `wiki:` respectively.

cc @bsrinivasa

**Comment by bsrinivasa** [comment]
I think this has been implemented in the script. Good to close this @amishas157 @planemad ?
