### ISSUE TITLE
osm.py replaces the last column in output

### ISSUE THREAD

**Issue by bsrinivasa** [amishas157/lookup-osm-wikidata#3]
The osm.py script replaces (erases) the last column from the input.csv while processing fetched fields are overwritten from the last column in output.csv resulting in the loss of data in that column. 

cc: @amishas157

**Comment by amishas157** [comment]
@bsrinivasa Fixed here: 4e392cea3cba5f135651d711a2258867681780b3
Thanks

**Comment by bsrinivasa** [comment]
Thanks for the fix. @amishas157  🎉 😄  Closing the issue!
