### ISSUE TITLE
Issue with `wiki:logs` in finalOutput.csv

### ISSUE THREAD

**Issue by bsrinivasa** [amishas157/lookup-osm-wikidata#6]
@amishas157 
The `wikilogs` in finalOutput.csv shows **`Wikidata API failure or no wikidata`** for those which did not have language translations. Would be great if this can be fixed.

_Priority: Medium_

**Comment by amishas157** [comment]
@bsrinivasa 
With the fix in this issue: https://github.com/amishas157/lookup-osm-wikidata/issues/7, this issue is fixed as well. Can you check once?

**Comment by bsrinivasa** [comment]
@amishas157 
I guess this is fixed. Thanks for the fix. Closing now. Would re open in case if there are issues.
