### ISSUE TITLE
Failures in wiki.py even though translations existed in the Wikidata

### ISSUE THREAD

**Issue by bsrinivasa** [amishas157/lookup-osm-wikidata#7]
When the **wiki.py** script was used to query _zh_, _zh-hans_ and _zh-cn_ languages from Wikidata, it failed with `wiki:logs - Wiki API Error` and when inspected for those ids in Wikidata, the translations for the corresponding translations were found. 
Here is the csv of the failures. 

`osm:wikidata,osm:wikipedia,osm:geometry,en,find.zh-hans,replace.zh-hans
Q1747725,,,Gopalpur,戈巴爾布爾,戈巴尔布尔
Q2299301,,,Pekan Tutong,北干都東,北干都东
Q1747725,,,Gopalpur,戈巴爾布爾,戈巴尔布尔
Q356898,,,Vinzons,賓松斯,宾松斯
Q155735,,,Burgos,布爾戈斯,布尔戈斯
Q1747725,,,Gopalpur,戈巴爾布爾,戈巴尔布尔
Q1747725,,,Gopalpur,戈巴爾布爾,戈巴尔布尔
Q4876087,,,Beagle Bay Community,Beagle灣社區,Beagle湾社区
Q2923580,,,Braidwood,布雷德伍德（新南威爾斯省）,布雷德伍德（新南威尔斯省）
Q1016277,,,Coonamble,庫南布爾,库南布尔
Q911376,,,Brewarrina,布雷沃里納,布雷沃里纳
Q311266,,,Khobar,拜爾,拜尔
Q2739703,,,Jerilderie,杰里爾德里（新南威爾斯省）,杰里尔德里（新南威尔斯省）
Q1277540,,,Plitvička Jezera,普利特維采,普利特维采
Q2120688,,,Gmina Oława,奧瓦瓦社區,奥瓦瓦社区
Q2119963,,,Gillingham,基寧咸,基宁咸
Q994255,,,Orašje,奥拿斯積,奥拿斯积
Q2120688,,,Gmina Oława,奧瓦瓦社區,奥瓦瓦社区
Q2151487,,,Quartier-Morin,夸提亞莫林,夸提亚莫林
Q2004754,,,Moss Landing,莫斯碼頭,莫斯码头
Q1949294,,,Wallingford,沃靈福德,沃灵福德
Q1645069,,,Noblesville,諾布爾斯維爾,诺布尔斯维尔
Q1784194,,,Little Rock Air Force Base,小岩城空軍基地,小岩城空军基地
Q1020942,,,Chatsworth,查兹窩斯,查兹窝斯
Q1961857,,,Lexington,萊克星敦,莱克星敦
Q3886924,,,Point of Rocks,巨岩點（Point of Rocks）,巨岩点（Point of Rocks）
Q9095935,,,Whitinsville,怀延斯维尔鎮,怀延斯维尔镇
Q939602,,,Corsicana,科西加納,科西加纳
Q957851,,,Plainview,普萊恩維爾,普莱恩维尔
Q2305817,,,Hingham,興咸,兴咸
Q2028273,,,Garner,加納,加纳
Q899515,,,Cuito Cuanavale,奎托夸納瓦萊,奎托夸纳瓦莱
Q2284812,,,Bhojpur District,波澤布爾縣,波泽布尔县
Q369007,,,Tukums municipality,圖庫姆斯自治市,图库姆斯自治市
`

Further, @planemad and I  tried to  out by querying dry and querying for different languages, it was success. But this failed for `zh` `zh-hans` and `zh-cn`.

@amishas157, would be great if you can inspect and fix this.

**Comment by planemad** [comment]
@amishas157 This is blocking https://github.com/mapbox/data/issues/2456#issuecomment-283940261

**Comment by amishas157** [comment]
Fixed https://github.com/amishas157/lookup-osm-wikidata/commit/04aa3f32523068b00f9c8c7334cee5c735b5855e

cc @bsrinivasa
