### ISSUE TITLE
Fill in wiki:wikidata whenever possible

### ISSUE THREAD

**Issue by planemad** [amishas157/lookup-osm-wikidata#8]
Currently `wiki:wikidata` field is not populated if the item already has `osm:wikidata`. Lets populate this for all entries to ensure consistency in the output. This also makes it easier for spreadhseet analysis to find out which entries are missing a wiki tag on OSM.

cc @amishas157

**Comment by bsrinivasa** [comment]
@planemad Not sure if I am adding some confusion here. `osm:wikidata` gives us wikidata present in OSM. For those featured which have a blank cell in this column are considered for missing a wikidata tag. 

Where as `wiki:wikidata` gives the _wikidata id_ derived from wikipedia link tagged in OSM. 
We could modify the script to concatenate them to wiki:wikidata column but it would be hard to find those wikidata ids derived from Wikipedia article. 

cc; @amishas157

**Comment by planemad** [comment]
@bsrinivasa rather simple, if `osm:wikidata` is absent and `wiki:wikidata` is present, then it was derived from the Wikipedia article
